version: "3.9"

services:
  web:
    build: .
    container_name: metro_web
    ports:
      - "80:80"
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    name: php82-mariadb104_php_network